server:
  port: 9090
spring:
  application:
    name: api-gateway-server
  #配置redis的参数
  redis:
    host: localhost
    port: 6379
  #配置SpringCloudGateway的路由
  cloud:
    gateway:
      routes:
        - id: user-service  #id是自定义的标识
          #uri: http://127.0.0.1:9001  #当访问9090端口时，自动把ip和端口替换为此uri
          uri: lb://userservice #根据微服务名称拉取请求路径
          predicates:
            - Path=/user/**  #自动匹配/user/**的路径
          filters:
            - name: RequestRateLimiter
              args:
                #使用SpEL从Spring容器中获取对象
                key-resolver: '#{@pathKeyResolver}'
                #令牌桶每秒填充的平均速率
                redis-rate-limiter.replenishRate: 1
                #令牌桶的容量
                redis-rate-limiter.burstCapacity: 3
      discovery:
        locator:
          enabled: true #开启根据微服务名称自动转发
          lower-case-service-id: true  #w微服务名称小写呈现

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
  instance:
    prefer-ip-address: true
